### PR TITLE
downport syntax

### PR DESCRIPTION
**Pull request by oblomov-dev**
ok, thanks for the information. opened this PR now for version 7.50.

The testclasses are added again, some might not work on lower releases, because of for example the use of "is instance of".

yes the names of the temp variables are automatically generated, renaming for a better understanding makes sense.

let me know if you need more from my side.

best regards.

### CODE REVIEW

**Comment by sandraros** [comment]
Thanks. Till I setup abaplint, could you change "is instance of" and other incompatible ABAP? (not sure if you did the abaplint config to work with 7.02 or other version)

**Comment by oblomov-dev** [comment]
yes i checked it for lower releases with abaplint. the test classes were full of incompatible syntax which were not automatically downportable, thats why i deleted them first. but now i also adjusted them. I replaced all cast, new, value and is instance of commands. as far as i know and if i did not overlook something it should work now also for lower releases. unfortunately i just have a abap trial developer system for testing.
let me know, if there is something else i can do on my side.

**Comment by sandraros** [comment]
Nice, thank you very much. At my side, I have currently access to systems from 7.40 to 7.58. Let me a few days to check all that (I'm quite busy currently), and after that I'll merge your PR.

**Comment by sandraros** [comment]
I merged your PR and did extra stuff to make it compatible with 7.02 after installing abaplint as per your instructions (that's great, thank you!). It will be easier to have all versions use the same code basis 7.02. In the end, I think I will keep the main branch empty except a README to link to each branch corresponding to one version. I have to update the branch `7.51` (currently the branch `main`) with the same syntax 7.02 as branch `7.50` but with the extra class for ENUM.

**Comment by oblomov-dev** [comment]
thank you, that sounds very good to me :)

**Pull request merged**
